services:
    _defaults: 
        autowire: true
        autoconfigure: true
    AXS\ApiBundle\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']

    AXS\ApiBundle\Controller\Api\:
        resource: '../../src/Controller/Api.php'
        arguments: 
            $user_entity: "\\App\\Entity\\User"
            $user_uid: "email"
